/* eslint camelcase: 0 */
export interface GrpcFriendshipRawPayload {
  account: string,
  my_account: string,
  account_alias: string,
  encodeUserName: string,
  nickname: string,
  sex: string,
  country: string,
  province: string,
  city: string,
  sign: string,
  headHDImgUrl: string,
  headImgUrl: string,
  check_msg: string,
  source: string,
  sourceNickname: string,
  sourceAccount: string,
  sourceGroupNumber: string,
}
